#version: '3.9'
services:
  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - yolo:/data/db
    networks:
      - ecommerce-network

  backend:
    build: ./backend   
    container_name: backend
    image: jkiruri/backend-image:v1.0.0
    ports:
      - "5000:5000"
    environment: 
      DB_URL: mongodb://mongodb:27017/   
    depends_on:
      - database
    networks:
      - ecommerce-network

  frontend:
    build: ./client   
    container_name: frontend
    image: jkiruri/client-image:v1.0.0
    ports:
      - "3000:80"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge

volumes:
  yolo:
    name: yolo
